require conf/machine/imx8mm-lpddr4-evk.conf

MACHINE_NAME = "iesy i.MX8M Mini OSM-SF (Eval Kit)"

IMAGE_FSTYPES += "wic.gz"

UBOOT_DTB_NAME = "iesy-imx8mm-eva-mi.dtb"
UBOOT_CONFIG_BASENAME = "iesy_imx8mm_eva_mi"

KERNEL_DEVICETREE = "\
	iesy/iesy-imx8mm-eva-mi.dtb \
	"

BBMASK += " \
	.linux-rockchip.*.bbappend \
	.u-boot-rockchip.*.bbappend \
	"

# fix vim / vim-tiny build error on XWayland
PACKAGECONFIG:remove_pn-vim = "${@bb.utils.contains('DISTRO_FEATURES', 'wayland x11', 'x11', '', d)}"
PACKAGECONFIG:remove_pn-vim-tiny = "${@bb.utils.contains('DISTRO_FEATURES', 'wayland x11', 'x11', '', d)}"

SERIAL_CONSOLES = "115200;ttymxc2"
ATF_BOOT_UART_BASE = "0x30880000"
TEE_LOAD_ADDR = "0x7e000000"

MACHINE_FEATURES:remove = "nxp8987-sdio optee "

DISTRO_FEATURES:remove = "optee"
IMAGE_INSTALL:remove = "optee-test optee-os optee-client"